{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace | quote }}
data:
{{ toYaml .Values.configmap.data | indent 2 }}
{{- end }}
