apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: humor-game-project
  namespace: argocd
spec:
  description: Secured GitOps Project for Dev, QA, and Prod
  sourceRepos:
  - 'https://github.com/shubhamksawant/lab2.git'

  destinations:
  - namespace: humor-game-dev
    server: https://kubernetes.default.svc
  - namespace: humor-game-qa
    server: https://kubernetes.default.svc
  - namespace: humor-game-prod
    server: https://kubernetes.default.svc
  - namespace: monitoring  # <--- ADD THIS LINE
    server: https://kubernetes.default.svc
  # Cluster resource allow list
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  # Namespace resource allow list (Restrictive)
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: 'apps'
    kind: Deployment
  - group: ''
    kind: Service
  - group: ''
    kind: PersistentVolumeClaim
  - group: ''
    kind: Secret # Added: usually needed for Helm/App secrets
  - group: ''
    kind: ServiceAccount      # Needed for Prometheus Identity
  - group: ''
    kind: PersistentVolumeClaim # Needed for Database/Metrics storage
  - group: 'monitoring.coreos.com'
    kind: ServiceMonitor      # Needed for your Custom Metrics scraping
  - group: '*'
    kind: '*'
  
  # Resource deny list (The "Blacklist")
  clusterResourceBlacklist:


  orphanedResources:
    warn: true

  signatureKeys: []
