{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
stringData:
{{ toYaml .Values.secrets.data | indent 2 }}
{{- end }}
